#!/bin/sh

ln -sf /opt/etc/pulse/filter_8000_44100.dat /opt/etc/pulse/filter_11025_44100.dat
ln -sf /opt/etc/pulse/filter_8000_44100.dat /opt/etc/pulse/filter_12000_44100.dat
ln -sf /opt/etc/pulse/filter_8000_44100.dat /opt/etc/pulse/filter_16000_44100.dat
ln -sf /opt/etc/pulse/filter_8000_44100.dat /opt/etc/pulse/filter_22050_44100.dat
ln -sf /opt/etc/pulse/filter_8000_44100.dat /opt/etc/pulse/filter_24000_44100.dat
ln -sf /opt/etc/pulse/filter_8000_44100.dat /opt/etc/pulse/filter_32000_44100.dat

